### ISSUE TITLE
Not able to use the pretrained model file

### ISSUE THREAD

**Issue by sg-pillai** [DASH-Lab/VFP290K#1] opened 2021-11-22 12:26 UTC
Hello,

Thank you for your work and for providing the dataset.

I wanted to try your pretrained models on some custom videos. But after downloading the pretrained weights (with an extension .egg) I am not able to use it by unzipping it.

Could you please let me know if it is a problem with the file or am I missing any steps?

Thank you.

**Comment by rlawjdghek** [comment] 2021-12-02 09:43
I check there are no issues downloading checkpoints from google drive and I successfully infer some videos. 

Could you give some details about what the problem is??

**Comment by anjaeju** [comment] 2021-12-02 09:48
+ Additive

The .egg file is not pretrained weights, it is the zip file for the pretrained weights.
You need to unzip it and use the model weights you want.

If it solved your issues, please close this issue.

**Comment by sg-pillai** [comment] 2021-12-03 09:44
Hello @anjaeju, @rlawjdghek,

Thank you for your response.
I have already tried unzipping it.

My issue is that I am not able to unzip it. I am getting the following error while trying to unzip it:
"End-of-central-directory signature not found."

I have tried the possible solutions for this error. I even downloaded the file again and tried it. But no luck.

**Comment by anjaeju** [comment] 2021-12-16 03:04
@sg-pillai 
We checked multiple times for downloading and loading the weights, and we successfully did it.
Can you check the download environment, such as there were no errors?
 
Also, we highly recommend 'Google Stream' for downloading some large files we provided.

**Comment by yhr321** [comment] 2022-01-11 04:33
Hello @sg-pillai，I also have the problem that I cannot unzip the egg file. Do you solve the problem?

**Comment by sg-pillai** [comment] 2022-01-11 16:38
> @sg-pillai We checked multiple times for downloading and loading the weights, and we successfully did it. Can you check the download environment, such as there were no errors?
> 
> Also, we highly recommend 'Google Stream' for downloading some large files we provided.

Hi @anjaeju,

I had checked that there were no errors in the environment.

**Comment by sg-pillai** [comment] 2022-01-11 16:43
> Hello @sg-pillai，I also have the problem that I cannot unzip the egg file. Do you solve the problem?

Hi @yhr321 ,
I tried downloading the file multiple times, but no luck as of now.

**Comment by sg-pillai** [comment] 2022-01-11 21:18
Hello @anjaeju, @rlawjdghek,

Also, the link for the checkpoints in the section "MMdetection-based models" (step 4) is not working.

**Closed as completed** 2022-02-10 07:16 UTC

**Comment by sg-pillai** [comment] 2022-02-10 07:18
The new zip file worked for me
